# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""Generated smoke suite — one method per resource over a mock transport."""

from __future__ import annotations

import json

import anyio
import httpx
from pydantic import TypeAdapter

from parcel_events_sdk_fixture_260904 import AsyncParcelEventsSdkFixture260904, ParcelEventsSdkFixture260904
from parcel_events_sdk_fixture_260904 import models


def _transport(steps: list[tuple[int, str | None, str]], calls: list[httpx.Request]) -> httpx.MockTransport:
    """A scripted transport: each step is (status, content_type, body)."""

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(request)
        status, content_type, body = steps.pop(0)
        headers = {} if content_type is None else {"content-type": content_type}
        return httpx.Response(status, headers=headers, content=body.encode("utf-8"))

    return httpx.MockTransport(handler)


def test_labels_create() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(201, "application/json", "{\"download_url\":\"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\"expires_at\":\"2026-06-09T00:00:00Z\",\"format\":\"pdf\",\"id\":\"lbl_00000000000000000001\",\"object\":\"label\",\"price\":{\"amount\":\"12.50\",\"currency\":\"XTS\"},\"shipment_id\":\"shp_00000000000000000001\"}")]
    client = ParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
    result = client.labels.create({
    "format": "pdf",
    "page_size": "four_by_six",
    "shipment_id": "shp_00000000000000000001",
}, idempotency_key="string")
    assert len(calls) == 1
    assert calls[0].method == "POST"
    adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
    assert result == adapter.validate_python(json.loads("{\"download_url\":\"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\"expires_at\":\"2026-06-09T00:00:00Z\",\"format\":\"pdf\",\"id\":\"lbl_00000000000000000001\",\"object\":\"label\",\"price\":{\"amount\":\"12.50\",\"currency\":\"XTS\"},\"shipment_id\":\"shp_00000000000000000001\"}"))


def test_pickups_cancel() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(204, None, "")]
    client = ParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
    client.pickups.cancel("string")
    assert len(calls) == 1
    assert calls[0].method == "DELETE"


def test_rates_quote() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(200, "application/json", "{\"data\":[{\"amount\":{\"amount\":\"string\",\"currency\":\"string\"},\"carrier\":\"string\",\"estimated_delivery_date\":\"string\",\"expires_at\":\"string\",\"id\":\"string\",\"service\":\"string\"}]}")]
    client = ParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
    result = client.rates.quote({
    "parcels": [
        {
            "contents": [
                {
                    "customs_code": "610910",
                    "description": "Synthetic cotton shirt",
                    "quantity": 2,
                    "unit_value": {
                        "amount": "12.50",
                        "currency": "XTS",
                    },
                },
            ],
            "height_cm": 12,
            "length_cm": 30.5,
            "weight_grams": 1750,
            "width_cm": 20,
        },
    ],
    "recipient": {
        "city": "Exampleton",
        "company": "Northstar Supplies",
        "country": "ZZ",
        "line1": "14 Fictional Quay",
        "line2": "Unit 7",
        "name": "Rowan Example",
        "phone": "+00000000000",
        "postal_code": "EX4 2PL",
        "region": "Test Province",
    },
    "sender": {
        "city": "Exampleton",
        "company": "Northstar Supplies",
        "country": "ZZ",
        "line1": "14 Fictional Quay",
        "line2": "Unit 7",
        "name": "Rowan Example",
        "phone": "+00000000000",
        "postal_code": "EX4 2PL",
        "region": "Test Province",
    },
})
    assert len(calls) == 1
    assert calls[0].method == "POST"
    adapter: TypeAdapter[models.RatesQuoteResponse] = TypeAdapter(models.RatesQuoteResponse)
    assert result == adapter.validate_python(json.loads("{\"data\":[{\"amount\":{\"amount\":\"string\",\"currency\":\"string\"},\"carrier\":\"string\",\"estimated_delivery_date\":\"string\",\"expires_at\":\"string\",\"id\":\"string\",\"service\":\"string\"}]}"))


def test_shipments_cancel() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(204, None, "")]
    client = ParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
    client.shipments.cancel("string")
    assert len(calls) == 1
    assert calls[0].method == "DELETE"


def test_shipments_events_list() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(200, "application/json", "{\"data\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"has_more\":true,\"next_cursor\":\"string\"}")]
    client = ParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
    result = client.shipments.events.list("string")
    assert len(calls) == 1
    assert calls[0].method == "GET"
    assert isinstance(result.items(), list)


def test_tracking_retrieve() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(200, "application/json", "{\"events\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"shipment\":{\"created_at\":\"2026-09-04T08:15:30Z\",\"delivery_instructions\":\"string\",\"id\":\"shp_00000000000000000001\",\"metadata\":{\"additionalProp1\":\"string\"},\"object\":\"shipment\",\"parcels\":[{\"contents\":[{\"customs_code\":\"610910\",\"description\":\"Synthetic cotton shirt\",\"quantity\":2,\"unit_value\":{\"amount\":\"12.50\",\"currency\":\"XTS\"}}],\"height_cm\":12,\"length_cm\":30.5,\"weight_grams\":1750,\"width_cm\":20}],\"recipient\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"reference\":\"synthetic-order-1042\",\"sender\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"service\":\"economy\",\"status\":\"canceled\",\"tracking_number\":\"PE-000000000001\",\"updated_at\":\"2026-09-04T08:16:12Z\"}}")]
    client = ParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
    result = client.tracking.retrieve("string")
    assert len(calls) == 1
    assert calls[0].method == "GET"
    adapter: TypeAdapter[models.TrackingTimeline] = TypeAdapter(models.TrackingTimeline)
    assert result == adapter.validate_python(json.loads("{\"events\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"shipment\":{\"created_at\":\"2026-09-04T08:15:30Z\",\"delivery_instructions\":\"string\",\"id\":\"shp_00000000000000000001\",\"metadata\":{\"additionalProp1\":\"string\"},\"object\":\"shipment\",\"parcels\":[{\"contents\":[{\"customs_code\":\"610910\",\"description\":\"Synthetic cotton shirt\",\"quantity\":2,\"unit_value\":{\"amount\":\"12.50\",\"currency\":\"XTS\"}}],\"height_cm\":12,\"length_cm\":30.5,\"weight_grams\":1750,\"width_cm\":20}],\"recipient\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"reference\":\"synthetic-order-1042\",\"sender\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"service\":\"economy\",\"status\":\"canceled\",\"tracking_number\":\"PE-000000000001\",\"updated_at\":\"2026-09-04T08:16:12Z\"}}"))


def test_webhook_endpoints_create() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(201, "application/json", "{\"created_at\":\"2026-06-09T00:00:00Z\",\"enabled\":true,\"events\":[\"pickup.completed\"],\"id\":\"whe_00000000000000000001\",\"object\":\"webhook_endpoint\",\"signing_secret_hint\":\"synthetic-key-ending-0000\",\"url\":\"https://hooks.parcel-events.example/events\"}")]
    client = ParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
    result = client.webhook_endpoints.create({
    "description": "string",
    "events": [
        "pickup.completed",
    ],
    "url": "https://hooks.parcel-events.example/events",
})
    assert len(calls) == 1
    assert calls[0].method == "POST"
    adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
    assert result == adapter.validate_python(json.loads("{\"created_at\":\"2026-06-09T00:00:00Z\",\"enabled\":true,\"events\":[\"pickup.completed\"],\"id\":\"whe_00000000000000000001\",\"object\":\"webhook_endpoint\",\"signing_secret_hint\":\"synthetic-key-ending-0000\",\"url\":\"https://hooks.parcel-events.example/events\"}"))


def test_labels_create_async() -> None:
    calls: list[httpx.Request] = []
    steps: list[tuple[int, str | None, str]] = [(201, "application/json", "{\"download_url\":\"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\"expires_at\":\"2026-06-09T00:00:00Z\",\"format\":\"pdf\",\"id\":\"lbl_00000000000000000001\",\"object\":\"label\",\"price\":{\"amount\":\"12.50\",\"currency\":\"XTS\"},\"shipment_id\":\"shp_00000000000000000001\"}")]

    async def main() -> None:
        client = AsyncParcelEventsSdkFixture260904(api_key="my-api-key", transport=_transport(steps, calls))
        result = await client.labels.create({
    "format": "pdf",
    "page_size": "four_by_six",
    "shipment_id": "shp_00000000000000000001",
}, idempotency_key="string")
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        assert result == adapter.validate_python(json.loads("{\"download_url\":\"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\"expires_at\":\"2026-06-09T00:00:00Z\",\"format\":\"pdf\",\"id\":\"lbl_00000000000000000001\",\"object\":\"label\",\"price\":{\"amount\":\"12.50\",\"currency\":\"XTS\"},\"shipment_id\":\"shp_00000000000000000001\"}"))

    anyio.run(main)
    assert len(calls) == 1
