# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""The generated client classes (sync + async) over the vendored kernel."""

from __future__ import annotations

import os
from typing import Any, Literal, Mapping

import httpx

from ._kernel._auth import AuthProvider, api_key_auth, bearer_auth
from ._kernel._client import SyncClient
from ._kernel._client_async import AsyncClient
from ._kernel._idempotency import IdempotencyConfig
from ._kernel._retries import RetryPolicy
from .resources.labels import AsyncLabels, Labels
from .resources.pickups import AsyncPickups, Pickups
from .resources.rates import AsyncRates, Rates
from .resources.shipments import AsyncShipments, Shipments
from .resources.tracking import AsyncTracking, Tracking
from .resources.webhook_endpoints import AsyncWebhookEndpoints, WebhookEndpoints

#: Named base URLs (`environments:` / the spec's servers).
environments: Mapping[str, str] = {
    "production": "https://api.parcel-events.example",
    "sandbox": "https://sandbox.parcel-events.example",
}

#: The IR-frozen retry defaults (`retries:` in `doctorine.sdk.yml`).
_DEFAULT_RETRIES = RetryPolicy(
    enabled=True,
    max_retries=3,
    initial_delay_ms=250,
    max_delay_ms=8000,
    max_elapsed_ms=60000,
    exponent=2,
    status_codes=(408, 409, 429, "5XX"),
    retry_connection_errors=True,
)


def _resolve_auth(
    *,
    api_key: str | None = None,
    bearer_token: str | None = None,
    transport: httpx.BaseTransport | None = None,
) -> AuthProvider | None:
    """The config's anyOf groups in order — the first satisfied group wins."""
    api_key_value = api_key if api_key is not None else os.environ.get("PARCEL_EVENTS_API_KEY")
    bearer_token_value = bearer_token if bearer_token is not None else os.environ.get("PARCEL_EVENTS_BEARER_TOKEN")
    providers: dict[str, AuthProvider | None] = {
        "api_key": api_key_auth(placement="header", name="Parcel-API-Key", key=api_key_value) if api_key_value is not None else None,
        "bearer_token": bearer_auth(bearer_token_value) if bearer_token_value is not None else None,
    }
    for group in (("api_key",), ("bearer_token",)):
        selected = [providers[name] for name in group]
        resolved = [provider for provider in selected if provider is not None]
        if len(resolved) == len(selected):
            return resolved[0]
    return None


def _resolve_auth_async(
    *,
    api_key: str | None = None,
    bearer_token: str | None = None,
    transport: httpx.AsyncBaseTransport | None = None,
) -> AuthProvider | None:
    """The config's anyOf groups in order — the first satisfied group wins."""
    api_key_value = api_key if api_key is not None else os.environ.get("PARCEL_EVENTS_API_KEY")
    bearer_token_value = bearer_token if bearer_token is not None else os.environ.get("PARCEL_EVENTS_BEARER_TOKEN")
    providers: dict[str, AuthProvider | None] = {
        "api_key": api_key_auth(placement="header", name="Parcel-API-Key", key=api_key_value) if api_key_value is not None else None,
        "bearer_token": bearer_auth(bearer_token_value) if bearer_token_value is not None else None,
    }
    for group in (("api_key",), ("bearer_token",)):
        selected = [providers[name] for name in group]
        resolved = [provider for provider in selected if provider is not None]
        if len(resolved) == len(selected):
            return resolved[0]
    return None


class ParcelEventsSdkFixture260904:
    """The synchronous `parcel-events-sdk-fixture-260904` client."""

    labels: Labels
    pickups: Pickups
    rates: Rates
    shipments: Shipments
    tracking: Tracking
    webhook_endpoints: WebhookEndpoints

    def __init__(
        self,
        *,
        base_url: str | None = None,
        environment: Literal["production", "sandbox"] = "production",
        api_key: str | None = None,
        bearer_token: str | None = None,
        timeout_ms: float = 45000,
        retries: RetryPolicy | None = None,
        default_headers: Mapping[str, str] | None = None,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        resolved_base_url = base_url if base_url is not None else environments[environment]
        self._client = SyncClient(
            base_url=resolved_base_url,
            auth=_resolve_auth(api_key=api_key, bearer_token=bearer_token, transport=transport),
            transport=transport,
            timeout_ms=timeout_ms,
            retries=retries if retries is not None else _DEFAULT_RETRIES,
            default_headers=default_headers,
            sdk_name="parcel-events-sdk-fixture-260904",
            sdk_version="0.1.1+sdk.c3477694933c",
            idempotency=IdempotencyConfig(header="Idempotency-Key", auto_generate=True),
        )
        self.labels = Labels(self._client)
        self.pickups = Pickups(self._client)
        self.rates = Rates(self._client)
        self.shipments = Shipments(self._client)
        self.tracking = Tracking(self._client)
        self.webhook_endpoints = WebhookEndpoints(self._client)

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> ParcelEventsSdkFixture260904:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()

    def retrieve(self, *args: Any, **kwargs: Any) -> Any:
        """`tracking.retrieve` attached to the client root (`$client: true`)."""
        return self.tracking.retrieve(*args, **kwargs)


class AsyncParcelEventsSdkFixture260904:
    """The asynchronous `parcel-events-sdk-fixture-260904` client."""

    labels: AsyncLabels
    pickups: AsyncPickups
    rates: AsyncRates
    shipments: AsyncShipments
    tracking: AsyncTracking
    webhook_endpoints: AsyncWebhookEndpoints

    def __init__(
        self,
        *,
        base_url: str | None = None,
        environment: Literal["production", "sandbox"] = "production",
        api_key: str | None = None,
        bearer_token: str | None = None,
        timeout_ms: float = 45000,
        retries: RetryPolicy | None = None,
        default_headers: Mapping[str, str] | None = None,
        transport: httpx.AsyncBaseTransport | None = None,
    ) -> None:
        resolved_base_url = base_url if base_url is not None else environments[environment]
        self._client = AsyncClient(
            base_url=resolved_base_url,
            auth=_resolve_auth_async(api_key=api_key, bearer_token=bearer_token, transport=transport),
            transport=transport,
            timeout_ms=timeout_ms,
            retries=retries if retries is not None else _DEFAULT_RETRIES,
            default_headers=default_headers,
            sdk_name="parcel-events-sdk-fixture-260904",
            sdk_version="0.1.1+sdk.c3477694933c",
            idempotency=IdempotencyConfig(header="Idempotency-Key", auto_generate=True),
        )
        self.labels = AsyncLabels(self._client)
        self.pickups = AsyncPickups(self._client)
        self.rates = AsyncRates(self._client)
        self.shipments = AsyncShipments(self._client)
        self.tracking = AsyncTracking(self._client)
        self.webhook_endpoints = AsyncWebhookEndpoints(self._client)

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> AsyncParcelEventsSdkFixture260904:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.close()

    async def retrieve(self, *args: Any, **kwargs: Any) -> Any:
        """`tracking.retrieve` attached to the client root (`$client: true`)."""
        return await self.tracking.retrieve(*args, **kwargs)
