# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""Base classes of every generated resource: kernel access + error remapping."""

from __future__ import annotations

from typing import Any, Mapping, NoReturn

import httpx
from pydantic import BaseModel

from ._kernel._client import APIResponse, SyncClient
from ._kernel._client_async import AsyncClient
from ._kernel._errors import APIError
from ._kernel._pagination_locators import PageRequest
from .errors import remap_error


def to_jsonable(value: Any) -> Any:
    """A JSON-plain payload from typed models / mappings / sequences."""
    if isinstance(value, BaseModel):
        return value.model_dump(mode="json", by_alias=True, exclude_unset=True)
    if isinstance(value, Mapping):
        return {key: to_jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [to_jsonable(item) for item in value]
    return value


def _raise_remapped(error: APIError) -> NoReturn:
    """Re-raise a kernel `APIError` as the most specific configured class."""
    remapped = remap_error(error)
    if remapped is error:
        raise error
    raise remapped from None


class SyncAPIResource:
    """Base class of every generated sync resource."""

    def __init__(self, client: SyncClient) -> None:
        self._client = client

    def _request(self, method: str, path: str, **options: Any) -> APIResponse[Any]:
        try:
            return self._client.request(method, path, **options)
        except APIError as error:
            _raise_remapped(error)

    def _request_stream(self, method: str, path: str, **options: Any) -> httpx.Response:
        try:
            return self._client.request_stream(method, path, **options)
        except APIError as error:
            _raise_remapped(error)

    def request_page(self, request: PageRequest) -> Any:
        """The pagination fetch hook (`SyncPageFetcher`)."""
        try:
            return self._client.request_page(request)
        except APIError as error:
            _raise_remapped(error)


class AsyncAPIResource:
    """Base class of every generated async resource."""

    def __init__(self, client: AsyncClient) -> None:
        self._client = client

    async def _request(self, method: str, path: str, **options: Any) -> APIResponse[Any]:
        try:
            return await self._client.request(method, path, **options)
        except APIError as error:
            _raise_remapped(error)

    async def _request_stream(self, method: str, path: str, **options: Any) -> httpx.Response:
        try:
            return await self._client.request_stream(method, path, **options)
        except APIError as error:
            _raise_remapped(error)

    async def request_page(self, request: PageRequest) -> Any:
        """The pagination fetch hook (`AsyncPageFetcher`)."""
        try:
            return await self._client.request_page(request)
        except APIError as error:
            _raise_remapped(error)
