# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""Typed error taxonomy: the kernel classes + configured error classes."""

from __future__ import annotations

from ._kernel._errors import (
    APIConnectionError,
    APIConnectionTimeoutError,
    APIError,
    BadRequestError,
    InternalServerError,
    PermissionDeniedError,
    UnprocessableEntityError,
)
from ._kernel._pagination_locators import read_body_pointer
from ._kernel._retries import StatusMatcher, status_matches

__all__ = [
    "APIConnectionError",
    "APIConnectionTimeoutError",
    "APIError",
    "AuthenticationError",
    "BadRequestError",
    "ConflictError",
    "InternalServerError",
    "NotFoundError",
    "PaymentRequiredError",
    "PermissionDeniedError",
    "RateLimitError",
    "ServerError",
    "UnprocessableEntityError",
    "ValidationError",
    "remap_error",
]


class AuthenticationError(APIError):
    """Configured error class — HTTP 401."""


class ConflictError(APIError):
    """Configured error class — HTTP 409."""


class NotFoundError(APIError):
    """Configured error class — HTTP 404."""


class PaymentRequiredError(APIError):
    """Configured error class — HTTP 402."""


class RateLimitError(APIError):
    """Configured error class — HTTP 429."""


class ServerError(APIError):
    """Configured error class — HTTP 5XX."""


class ValidationError(APIError):
    """Configured error class — HTTP 422 when `/type` = "https://parcel-events.example/problems/validation"."""


# The IR's frozen (className-sorted) order — the FIRST matching entry wins.
_ERROR_MAP: tuple[tuple[type[APIError], tuple[StatusMatcher, ...], tuple[str, str | None] | None], ...] = (
    (AuthenticationError, (401,), None),
    (ConflictError, (409,), None),
    (NotFoundError, (404,), None),
    (PaymentRequiredError, (402,), None),
    (RateLimitError, (429,), None),
    (ServerError, ("5XX",), None),
    (ValidationError, (422,), ("$.type", "https://parcel-events.example/problems/validation")),
)


def remap_error(error: BaseException) -> BaseException:
    """Re-type a kernel `APIError` into the most specific configured class."""
    if not isinstance(error, APIError):
        return error
    for cls, statuses, shape in _ERROR_MAP:
        if isinstance(error, cls):
            return error
        if not any(status_matches(error.status, matcher) for matcher in statuses):
            continue
        if shape is not None:
            value = read_body_pointer(error.body, shape[0])
            matched = value is not None if shape[1] is None else value == shape[1]
            if not matched:
                continue
        return cls(status=error.status, headers=error.headers, body=error.body, message=str(error))
    return error
