# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""Typed models generated from the API specification."""

from __future__ import annotations

from typing import Annotated, Any, List, Literal, TypeAlias

from pydantic import BaseModel, BeforeValidator, ConfigDict, model_validator
from ._kernel._constraints import constraint_validator


class Address(BaseModel):
    """Address — #/components/schemas/Address"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    city: str
    company: str | None = None
    country: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^[A-Z]{2}$"}))]
    line1: str
    line2: str | None = None
    name: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]
    phone: str | None = None
    postal_code: str
    region: str | None = None


class CreateLabelRequest(BaseModel):
    """CreateLabelRequest — #/components/schemas/CreateLabelRequest"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    format: LabelFormat
    page_size: Literal["a4", "letter", "four_by_six"] | None = None
    shipment_id: str


class CreatePickupRequest(BaseModel):
    """CreatePickupRequest — #/components/schemas/CreatePickupRequest"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    address: Address
    notes: Annotated[str | None, BeforeValidator(constraint_validator({"maxLength": 500}))] | None = None
    shipment_ids: Annotated[List[str], BeforeValidator(constraint_validator({"minItems": 1, "maxItems": 100}))]
    window: PickupWindow


class CreateShipmentRequest(BaseModel):
    """CreateShipmentRequest — #/components/schemas/CreateShipmentRequest"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    delivery_instructions: Annotated[str | None, BeforeValidator(constraint_validator({"maxLength": 500}))] | None = None
    metadata: Annotated[dict[str, str], BeforeValidator(constraint_validator({"maxProperties": 20}))] | None = None
    parcels: Annotated[List[Parcel], BeforeValidator(constraint_validator({"minItems": 1, "maxItems": 20}))]
    recipient: Address
    reference: Annotated[str, BeforeValidator(constraint_validator({"maxLength": 80}))]
    sender: Address
    service: Literal["economy", "express", "same_day"]


class CreateWebhookEndpointRequest(BaseModel):
    """CreateWebhookEndpointRequest — #/components/schemas/CreateWebhookEndpointRequest"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    description: Annotated[str | None, BeforeValidator(constraint_validator({"maxLength": 120}))] | None = None
    events: Annotated[List[WebhookEventType], BeforeValidator(constraint_validator({"minItems": 1, "uniqueItems": True}))]
    url: str


class Label(BaseModel):
    """Label — #/components/schemas/Label"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    download_url: str
    expires_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    format: LabelFormat
    id: str
    object: Literal["label"]
    price: Money
    shipment_id: str


class Money(BaseModel):
    """Money — #/components/schemas/Money"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    amount: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^[0-9]+(\\.[0-9]{2})$"}))]
    currency: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^[A-Z]{3}$"}))]


class Parcel(BaseModel):
    """Parcel — #/components/schemas/Parcel"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    contents: Annotated[List[ParcelItem], BeforeValidator(constraint_validator({"maxItems": 50}))] | None = None
    height_cm: Annotated[float, BeforeValidator(constraint_validator({"exclusiveMinimum": 0}))]
    length_cm: Annotated[float, BeforeValidator(constraint_validator({"exclusiveMinimum": 0}))]
    weight_grams: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1}))]
    width_cm: Annotated[float, BeforeValidator(constraint_validator({"exclusiveMinimum": 0}))]


class ParcelItem(BaseModel):
    """ParcelItem — #/components/schemas/ParcelItem"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    customs_code: str | None = None
    description: str
    quantity: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1}))]
    unit_value: Money


class Pickup(BaseModel):
    """Pickup — #/components/schemas/Pickup"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    address: Address
    created_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    id: str
    object: Literal["pickup"]
    shipment_ids: List[str]
    status: Literal["scheduled", "completed", "canceled", "missed"]
    window: PickupWindow


class PickupPage(BaseModel):
    """PickupPage — #/components/schemas/PickupPage"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    data: List[Pickup]
    has_more: bool
    next_cursor: str | None


class PickupWindow(BaseModel):
    """PickupWindow — #/components/schemas/PickupWindow"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    ends_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    starts_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]


class RateQuote(BaseModel):
    """RateQuote — #/components/schemas/RateQuote"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    amount: Money
    carrier: str
    estimated_delivery_date: Annotated[str, BeforeValidator(constraint_validator({"format": "date"}))]
    expires_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    id: str
    service: str


class RateQuoteRequest(BaseModel):
    """RateQuoteRequest — #/components/schemas/RateQuoteRequest"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    parcels: Annotated[List[Parcel], BeforeValidator(constraint_validator({"minItems": 1}))]
    recipient: Address
    sender: Address


class RatesQuoteResponse(BaseModel):
    """RatesQuoteResponse — synthesized:RatesQuoteResponse"""

    model_config = ConfigDict(populate_by_name=True, extra="allow")
    data: List[RateQuote]


class Shipment(BaseModel):
    """Shipment — #/components/schemas/Shipment"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    created_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    delivery_instructions: str | None = None
    id: str
    metadata: dict[str, str] | None = None
    object: Literal["shipment"]
    parcels: List[Parcel]
    recipient: Address
    reference: str
    sender: Address
    service: Literal["economy", "express", "same_day"]
    status: ShipmentStatus
    tracking_number: str
    updated_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]


class ShipmentPage(BaseModel):
    """ShipmentPage — #/components/schemas/ShipmentPage"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    data: List[Shipment]
    has_more: bool
    next_cursor: str | None


class ShipmentStatusEvent(BaseModel):
    """ShipmentStatusEvent — #/components/schemas/ShipmentStatusEvent"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    created_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    data: ShipmentStatusEventData
    id: str
    type: Literal["shipment.status_changed"]


class ShipmentStatusEventData(BaseModel):
    """ShipmentStatusEventData — synthesized:ShipmentStatusEventData"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    event: TrackingEvent
    shipment: Shipment


class TrackingEvent(BaseModel):
    """TrackingEvent — #/components/schemas/TrackingEvent"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    id: str
    location: TrackingEventLocation
    message: str | None = None
    object: Literal["tracking_event"]
    occurred_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    shipment_id: str
    status: ShipmentStatus


class TrackingEventLocation(BaseModel):
    """TrackingEventLocation — synthesized:TrackingEventLocation"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    city: str
    country: str


class TrackingEventPage(BaseModel):
    """TrackingEventPage — #/components/schemas/TrackingEventPage"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    data: List[TrackingEvent]
    has_more: bool
    next_cursor: str | None


class TrackingTimeline(BaseModel):
    """TrackingTimeline — #/components/schemas/TrackingTimeline"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    events: List[TrackingEvent]
    shipment: Shipment


class UpdateShipmentRequest(BaseModel):
    """UpdateShipmentRequest — #/components/schemas/UpdateShipmentRequest"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    @model_validator(mode="before")
    @classmethod
    def validate_schema_constraints(cls, value: Any) -> Any:
        return constraint_validator({"minProperties": 1})(value)

    delivery_instructions: Annotated[str | None, BeforeValidator(constraint_validator({"maxLength": 500}))] | None = None
    metadata: dict[str, str] | None = None


class UpdateWebhookEndpointRequest(BaseModel):
    """UpdateWebhookEndpointRequest — #/components/schemas/UpdateWebhookEndpointRequest"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    @model_validator(mode="before")
    @classmethod
    def validate_schema_constraints(cls, value: Any) -> Any:
        return constraint_validator({"minProperties": 1})(value)

    enabled: bool | None = None
    events: Annotated[List[WebhookEventType], BeforeValidator(constraint_validator({"minItems": 1, "uniqueItems": True}))] | None = None
    url: str | None = None


class WebhookEndpoint(BaseModel):
    """WebhookEndpoint — #/components/schemas/WebhookEndpoint"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    created_at: Annotated[str, BeforeValidator(constraint_validator({"format": "date-time"}))]
    enabled: bool
    events: List[WebhookEventType]
    id: str
    object: Literal["webhook_endpoint"]
    signing_secret_hint: str | None = None
    url: str


class WebhookEndpointPage(BaseModel):
    """WebhookEndpointPage — #/components/schemas/WebhookEndpointPage"""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
    data: List[WebhookEndpoint]
    has_more: bool
    next_cursor: str | None


LabelFormat: TypeAlias = Literal["pdf", "png", "zpl"]
"""LabelFormat — #/components/schemas/LabelFormat"""


ShipmentStatus: TypeAlias = Literal["draft", "label_purchased", "in_transit", "out_for_delivery", "delivered", "exception", "canceled"]
"""ShipmentStatus — #/components/schemas/ShipmentStatus"""


WebhookEventType: TypeAlias = Literal["shipment.created", "shipment.status_changed", "shipment.delivered", "shipment.exception", "pickup.completed"]
"""WebhookEventType — #/components/schemas/WebhookEventType"""


Address.model_rebuild()
CreateLabelRequest.model_rebuild()
CreatePickupRequest.model_rebuild()
CreateShipmentRequest.model_rebuild()
CreateWebhookEndpointRequest.model_rebuild()
Label.model_rebuild()
Money.model_rebuild()
Parcel.model_rebuild()
ParcelItem.model_rebuild()
Pickup.model_rebuild()
PickupPage.model_rebuild()
PickupWindow.model_rebuild()
RateQuote.model_rebuild()
RateQuoteRequest.model_rebuild()
RatesQuoteResponse.model_rebuild()
Shipment.model_rebuild()
ShipmentPage.model_rebuild()
ShipmentStatusEvent.model_rebuild()
ShipmentStatusEventData.model_rebuild()
TrackingEvent.model_rebuild()
TrackingEventLocation.model_rebuild()
TrackingEventPage.model_rebuild()
TrackingTimeline.model_rebuild()
UpdateShipmentRequest.model_rebuild()
UpdateWebhookEndpointRequest.model_rebuild()
WebhookEndpoint.model_rebuild()
WebhookEndpointPage.model_rebuild()
