# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""Run with: python examples/labels.py"""

from parcel_events_sdk_fixture_260904 import ParcelEventsSdkFixture260904

client = ParcelEventsSdkFixture260904(api_key="my-api-key")

result = client.labels.create({
    "format": "pdf",
    "page_size": "four_by_six",
    "shipment_id": "shp_00000000000000000001",
}, idempotency_key="string")
print(result)
