# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""Run with: python examples/pickups.py"""

from parcel_events_sdk_fixture_260904 import ParcelEventsSdkFixture260904

client = ParcelEventsSdkFixture260904(api_key="my-api-key")

client.pickups.cancel("pku_00000000000000000000")
print("ok")
