# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
"""Run with: python examples/webhook_endpoints.py"""

from parcel_events_sdk_fixture_260904 import ParcelEventsSdkFixture260904

client = ParcelEventsSdkFixture260904(api_key="my-api-key")

result = client.webhook_endpoints.create({
    "description": "string",
    "events": [
        "pickup.completed",
    ],
    "url": "https://hooks.parcel-events.example/events",
})
print(result)
