# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from urllib.parse import quote

from typing import Any, Mapping

from pydantic import TypeAdapter

from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class Labels(SyncAPIResource):
    """The sync `labels` resource."""

    def create(self, body: models.CreateLabelRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Label:
        """Buy and render a shipping label

        `POST /v1/labels` (`createLabel`)
        """
        response = self._request(
            "POST",
            "/v1/labels",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data)

    def retrieve(self, label_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Label:
        """Retrieve label metadata and download URL

        `GET /v1/labels/{label_id}` (`retrieveLabel`)
        """
        response = self._request(
            "GET",
            f"/v1/labels/{quote(str(label_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data)


class AsyncLabels(AsyncAPIResource):
    """The async `labels` resource."""

    async def create(self, body: models.CreateLabelRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Label:
        """Buy and render a shipping label

        `POST /v1/labels` (`createLabel`)
        """
        response = await self._request(
            "POST",
            "/v1/labels",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data)

    async def retrieve(self, label_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Label:
        """Retrieve label metadata and download URL

        `GET /v1/labels/{label_id}` (`retrieveLabel`)
        """
        response = await self._request(
            "GET",
            f"/v1/labels/{quote(str(label_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data)
