# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Any, Mapping

from pydantic import BeforeValidator, TypeAdapter

from .._kernel._constraints import constraint_validator
from .._kernel._serialization import encode_path_parameter
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class Labels(SyncAPIResource):
    """The sync `labels` resource."""

    def create(self, body: models.CreateLabelRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Label:
        """Buy and render a shipping label

        `POST /v1/labels` (`createLabel`)
        """
        TypeAdapter(models.CreateLabelRequest).validate_python(body, strict=True)
        response = self._request(
            "POST",
            "/v1/labels",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data, strict=True)

    def retrieve(self, label_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^lbl_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Label:
        """Retrieve label metadata and download URL

        `GET /v1/labels/{label_id}` (`retrieveLabel`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^lbl_[a-z0-9]{20}$"}))]).validate_python(label_id, strict=True)
        response = self._request(
            "GET",
            "/v1/labels/{label_id}".replace("{label_id}", encode_path_parameter("label_id", to_jsonable(label_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data, strict=True)


class AsyncLabels(AsyncAPIResource):
    """The async `labels` resource."""

    async def create(self, body: models.CreateLabelRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Label:
        """Buy and render a shipping label

        `POST /v1/labels` (`createLabel`)
        """
        TypeAdapter(models.CreateLabelRequest).validate_python(body, strict=True)
        response = await self._request(
            "POST",
            "/v1/labels",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data, strict=True)

    async def retrieve(self, label_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^lbl_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Label:
        """Retrieve label metadata and download URL

        `GET /v1/labels/{label_id}` (`retrieveLabel`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^lbl_[a-z0-9]{20}$"}))]).validate_python(label_id, strict=True)
        response = await self._request(
            "GET",
            "/v1/labels/{label_id}".replace("{label_id}", encode_path_parameter("label_id", to_jsonable(label_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Label] = TypeAdapter(models.Label)
        return adapter.validate_python(response.data, strict=True)
