# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Any, Mapping

from pydantic import BeforeValidator, TypeAdapter

from .._kernel._constraints import constraint_validator
from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._kernel._serialization import encode_path_parameter
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class Pickups(SyncAPIResource):
    """The sync `pickups` resource."""

    def cancel(self, pickup_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a pickup

        `DELETE /v1/pickups/{pickup_id}` (`cancelPickup`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))]).validate_python(pickup_id, strict=True)
        self._request(
            "DELETE",
            "/v1/pickups/{pickup_id}".replace("{pickup_id}", encode_path_parameter("pickup_id", to_jsonable(pickup_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    def create(self, body: models.CreatePickupRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Pickup:
        """Schedule a carrier pickup

        `POST /v1/pickups` (`createPickup`)
        """
        TypeAdapter(models.CreatePickupRequest).validate_python(body, strict=True)
        response = self._request(
            "POST",
            "/v1/pickups",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data, strict=True)

    def list(self, *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, scheduled_on: Annotated[str, BeforeValidator(constraint_validator({"format": "date"}))] | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> SyncPage[models.Pickup]:
        """List scheduled pickups

        `GET /v1/pickups` (`listPickups`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        if scheduled_on is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"format": "date"}))]).validate_python(scheduled_on, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        if scheduled_on is not None:
            query["scheduled_on"] = to_jsonable(scheduled_on)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/pickups",
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}, "scheduled_on": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return SyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.PickupPage).validate_python(envelope, strict=True))

    def retrieve(self, pickup_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Pickup:
        """Retrieve a pickup

        `GET /v1/pickups/{pickup_id}` (`retrievePickup`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))]).validate_python(pickup_id, strict=True)
        response = self._request(
            "GET",
            "/v1/pickups/{pickup_id}".replace("{pickup_id}", encode_path_parameter("pickup_id", to_jsonable(pickup_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data, strict=True)


class AsyncPickups(AsyncAPIResource):
    """The async `pickups` resource."""

    async def cancel(self, pickup_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a pickup

        `DELETE /v1/pickups/{pickup_id}` (`cancelPickup`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))]).validate_python(pickup_id, strict=True)
        await self._request(
            "DELETE",
            "/v1/pickups/{pickup_id}".replace("{pickup_id}", encode_path_parameter("pickup_id", to_jsonable(pickup_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    async def create(self, body: models.CreatePickupRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Pickup:
        """Schedule a carrier pickup

        `POST /v1/pickups` (`createPickup`)
        """
        TypeAdapter(models.CreatePickupRequest).validate_python(body, strict=True)
        response = await self._request(
            "POST",
            "/v1/pickups",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data, strict=True)

    async def list(self, *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, scheduled_on: Annotated[str, BeforeValidator(constraint_validator({"format": "date"}))] | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> AsyncPage[models.Pickup]:
        """List scheduled pickups

        `GET /v1/pickups` (`listPickups`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        if scheduled_on is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"format": "date"}))]).validate_python(scheduled_on, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        if scheduled_on is not None:
            query["scheduled_on"] = to_jsonable(scheduled_on)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/pickups",
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}, "scheduled_on": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return AsyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.PickupPage).validate_python(envelope, strict=True))

    async def retrieve(self, pickup_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Pickup:
        """Retrieve a pickup

        `GET /v1/pickups/{pickup_id}` (`retrievePickup`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^pku_[a-z0-9]{20}$"}))]).validate_python(pickup_id, strict=True)
        response = await self._request(
            "GET",
            "/v1/pickups/{pickup_id}".replace("{pickup_id}", encode_path_parameter("pickup_id", to_jsonable(pickup_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data, strict=True)
