# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from urllib.parse import quote

from typing import Any, Mapping

from pydantic import TypeAdapter

from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class Pickups(SyncAPIResource):
    """The sync `pickups` resource."""

    def cancel(self, pickup_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a pickup

        `DELETE /v1/pickups/{pickup_id}` (`cancelPickup`)
        """
        self._request(
            "DELETE",
            f"/v1/pickups/{quote(str(pickup_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    def create(self, body: models.CreatePickupRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Pickup:
        """Schedule a carrier pickup

        `POST /v1/pickups` (`createPickup`)
        """
        response = self._request(
            "POST",
            "/v1/pickups",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data)

    def list(self, *, cursor: str | None = None, limit: int | None = None, scheduled_on: str | None = None, extra_headers: Mapping[str, str] | None = None) -> SyncPage[models.Pickup]:
        """List scheduled pickups

        `GET /v1/pickups` (`listPickups`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        if scheduled_on is not None:
            query["scheduled_on"] = scheduled_on
        request = PageRequest(
            method="GET",
            url="/v1/pickups",
            query=query,
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return SyncPage(self, request, first, scheme, cast_item=adapter.validate_python)

    def retrieve(self, pickup_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Pickup:
        """Retrieve a pickup

        `GET /v1/pickups/{pickup_id}` (`retrievePickup`)
        """
        response = self._request(
            "GET",
            f"/v1/pickups/{quote(str(pickup_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data)


class AsyncPickups(AsyncAPIResource):
    """The async `pickups` resource."""

    async def cancel(self, pickup_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a pickup

        `DELETE /v1/pickups/{pickup_id}` (`cancelPickup`)
        """
        await self._request(
            "DELETE",
            f"/v1/pickups/{quote(str(pickup_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    async def create(self, body: models.CreatePickupRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Pickup:
        """Schedule a carrier pickup

        `POST /v1/pickups` (`createPickup`)
        """
        response = await self._request(
            "POST",
            "/v1/pickups",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data)

    async def list(self, *, cursor: str | None = None, limit: int | None = None, scheduled_on: str | None = None, extra_headers: Mapping[str, str] | None = None) -> AsyncPage[models.Pickup]:
        """List scheduled pickups

        `GET /v1/pickups` (`listPickups`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        if scheduled_on is not None:
            query["scheduled_on"] = scheduled_on
        request = PageRequest(
            method="GET",
            url="/v1/pickups",
            query=query,
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return AsyncPage(self, request, first, scheme, cast_item=adapter.validate_python)

    async def retrieve(self, pickup_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Pickup:
        """Retrieve a pickup

        `GET /v1/pickups/{pickup_id}` (`retrievePickup`)
        """
        response = await self._request(
            "GET",
            f"/v1/pickups/{quote(str(pickup_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Pickup] = TypeAdapter(models.Pickup)
        return adapter.validate_python(response.data)
