# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from typing import Any, Mapping

from pydantic import TypeAdapter

from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class Rates(SyncAPIResource):
    """The sync `rates` resource."""

    def quote(self, body: models.RateQuoteRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.RatesQuoteResponse:
        """Quote available shipping services

        `POST /v1/rates/quote` (`quoteRates`)
        """
        response = self._request(
            "POST",
            "/v1/rates/quote",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.RatesQuoteResponse] = TypeAdapter(models.RatesQuoteResponse)
        return adapter.validate_python(response.data)


class AsyncRates(AsyncAPIResource):
    """The async `rates` resource."""

    async def quote(self, body: models.RateQuoteRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.RatesQuoteResponse:
        """Quote available shipping services

        `POST /v1/rates/quote` (`quoteRates`)
        """
        response = await self._request(
            "POST",
            "/v1/rates/quote",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.RatesQuoteResponse] = TypeAdapter(models.RatesQuoteResponse)
        return adapter.validate_python(response.data)
