# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Any, Mapping

from pydantic import BeforeValidator, TypeAdapter

from .._kernel._client import SyncClient
from .._kernel._client_async import AsyncClient
from .._kernel._constraints import constraint_validator
from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._kernel._serialization import encode_path_parameter
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models
from .shipments_events import AsyncEvents, Events


class Shipments(SyncAPIResource):
    """The sync `shipments` resource."""

    def __init__(self, client: SyncClient) -> None:
        super().__init__(client)
        self.events = Events(client)

    def cancel(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a shipment before handoff

        `DELETE /v1/shipments/{shipment_id}` (`cancelShipment`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        self._request(
            "DELETE",
            "/v1/shipments/{shipment_id}".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    def create(self, body: models.CreateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Shipment:
        """Create a shipment

        `POST /v1/shipments` (`createShipment`)
        """
        TypeAdapter(models.CreateShipmentRequest).validate_python(body, strict=True)
        response = self._request(
            "POST",
            "/v1/shipments",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data, strict=True)

    def list(self, *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, status: models.ShipmentStatus | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> SyncPage[models.Shipment]:
        """List shipments

        `GET /v1/shipments` (`listShipments`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        if status is not None:
            TypeAdapter(models.ShipmentStatus).validate_python(status, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        if status is not None:
            query["status"] = to_jsonable(status)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/shipments",
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}, "status": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return SyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.ShipmentPage).validate_python(envelope, strict=True))

    def retrieve(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Retrieve a shipment

        `GET /v1/shipments/{shipment_id}` (`retrieveShipment`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        response = self._request(
            "GET",
            "/v1/shipments/{shipment_id}".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data, strict=True)

    def update(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], body: models.UpdateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Update delivery instructions

        `PATCH /v1/shipments/{shipment_id}` (`updateShipment`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        TypeAdapter(models.UpdateShipmentRequest).validate_python(body, strict=True)
        response = self._request(
            "PATCH",
            "/v1/shipments/{shipment_id}".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data, strict=True)


class AsyncShipments(AsyncAPIResource):
    """The async `shipments` resource."""

    def __init__(self, client: AsyncClient) -> None:
        super().__init__(client)
        self.events = AsyncEvents(client)

    async def cancel(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a shipment before handoff

        `DELETE /v1/shipments/{shipment_id}` (`cancelShipment`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        await self._request(
            "DELETE",
            "/v1/shipments/{shipment_id}".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    async def create(self, body: models.CreateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Shipment:
        """Create a shipment

        `POST /v1/shipments` (`createShipment`)
        """
        TypeAdapter(models.CreateShipmentRequest).validate_python(body, strict=True)
        response = await self._request(
            "POST",
            "/v1/shipments",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data, strict=True)

    async def list(self, *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, status: models.ShipmentStatus | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> AsyncPage[models.Shipment]:
        """List shipments

        `GET /v1/shipments` (`listShipments`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        if status is not None:
            TypeAdapter(models.ShipmentStatus).validate_python(status, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        if status is not None:
            query["status"] = to_jsonable(status)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/shipments",
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}, "status": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return AsyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.ShipmentPage).validate_python(envelope, strict=True))

    async def retrieve(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Retrieve a shipment

        `GET /v1/shipments/{shipment_id}` (`retrieveShipment`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        response = await self._request(
            "GET",
            "/v1/shipments/{shipment_id}".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data, strict=True)

    async def update(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], body: models.UpdateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Update delivery instructions

        `PATCH /v1/shipments/{shipment_id}` (`updateShipment`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        TypeAdapter(models.UpdateShipmentRequest).validate_python(body, strict=True)
        response = await self._request(
            "PATCH",
            "/v1/shipments/{shipment_id}".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data, strict=True)
