# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Mapping

from pydantic import BeforeValidator, TypeAdapter

from .._kernel._constraints import constraint_validator
from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._kernel._serialization import encode_path_parameter
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class Events(SyncAPIResource):
    """The sync `events` resource."""

    def list(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> SyncPage[models.TrackingEvent]:
        """List tracking events for a shipment

        `GET /v1/shipments/{shipment_id}/events` (`listShipmentEvents`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/shipments/{shipment_id}/events".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.TrackingEvent] = TypeAdapter(models.TrackingEvent)
        return SyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.TrackingEventPage).validate_python(envelope, strict=True))


class AsyncEvents(AsyncAPIResource):
    """The async `events` resource."""

    async def list(self, shipment_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))], *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> AsyncPage[models.TrackingEvent]:
        """List tracking events for a shipment

        `GET /v1/shipments/{shipment_id}/events` (`listShipmentEvents`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^shp_[a-z0-9]{20}$"}))]).validate_python(shipment_id, strict=True)
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/shipments/{shipment_id}/events".replace("{shipment_id}", encode_path_parameter("shipment_id", to_jsonable(shipment_id), {"style": "simple", "explode": False, "allowReserved": False})),
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.TrackingEvent] = TypeAdapter(models.TrackingEvent)
        return AsyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.TrackingEventPage).validate_python(envelope, strict=True))
