# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from urllib.parse import quote

from typing import Mapping

from pydantic import TypeAdapter

from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._resource import AsyncAPIResource, SyncAPIResource
from .. import models


class Events(SyncAPIResource):
    """The sync `events` resource."""

    def list(self, shipment_id: str, *, cursor: str | None = None, limit: int | None = None, extra_headers: Mapping[str, str] | None = None) -> SyncPage[models.TrackingEvent]:
        """List tracking events for a shipment

        `GET /v1/shipments/{shipment_id}/events` (`listShipmentEvents`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        request = PageRequest(
            method="GET",
            url=f"/v1/shipments/{quote(str(shipment_id), safe='')}/events",
            query=query,
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.TrackingEvent] = TypeAdapter(models.TrackingEvent)
        return SyncPage(self, request, first, scheme, cast_item=adapter.validate_python)


class AsyncEvents(AsyncAPIResource):
    """The async `events` resource."""

    async def list(self, shipment_id: str, *, cursor: str | None = None, limit: int | None = None, extra_headers: Mapping[str, str] | None = None) -> AsyncPage[models.TrackingEvent]:
        """List tracking events for a shipment

        `GET /v1/shipments/{shipment_id}/events` (`listShipmentEvents`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        request = PageRequest(
            method="GET",
            url=f"/v1/shipments/{quote(str(shipment_id), safe='')}/events",
            query=query,
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.TrackingEvent] = TypeAdapter(models.TrackingEvent)
        return AsyncPage(self, request, first, scheme, cast_item=adapter.validate_python)
