# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from urllib.parse import quote

from typing import Any, Mapping, cast

from pydantic import TypeAdapter

from .._kernel._client import SyncClient
from .._kernel._client_async import AsyncClient
from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models
from .shipments_events import AsyncEvents, Events


class Shipments(SyncAPIResource):
    """The sync `shipments` resource."""

    def __init__(self, client: SyncClient) -> None:
        super().__init__(client)
        self.events = Events(client)

    def cancel(self, shipment_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a shipment before handoff

        `DELETE /v1/shipments/{shipment_id}` (`cancelShipment`)
        """
        self._request(
            "DELETE",
            f"/v1/shipments/{quote(str(shipment_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    def create(self, body: models.CreateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Shipment:
        """Create a shipment

        `POST /v1/shipments` (`createShipment`)
        """
        response = self._request(
            "POST",
            "/v1/shipments",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data)

    def list(self, *, cursor: str | None = None, limit: int | None = None, status: models.ShipmentStatus | None = None, extra_headers: Mapping[str, str] | None = None) -> SyncPage[models.Shipment]:
        """List shipments

        `GET /v1/shipments` (`listShipments`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        if status is not None:
            query["status"] = cast(PageQueryValue, status)
        request = PageRequest(
            method="GET",
            url="/v1/shipments",
            query=query,
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return SyncPage(self, request, first, scheme, cast_item=adapter.validate_python)

    def retrieve(self, shipment_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Retrieve a shipment

        `GET /v1/shipments/{shipment_id}` (`retrieveShipment`)
        """
        response = self._request(
            "GET",
            f"/v1/shipments/{quote(str(shipment_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data)

    def update(self, shipment_id: str, body: models.UpdateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Update delivery instructions

        `PATCH /v1/shipments/{shipment_id}` (`updateShipment`)
        """
        response = self._request(
            "PATCH",
            f"/v1/shipments/{quote(str(shipment_id), safe='')}",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data)


class AsyncShipments(AsyncAPIResource):
    """The async `shipments` resource."""

    def __init__(self, client: AsyncClient) -> None:
        super().__init__(client)
        self.events = AsyncEvents(client)

    async def cancel(self, shipment_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Cancel a shipment before handoff

        `DELETE /v1/shipments/{shipment_id}` (`cancelShipment`)
        """
        await self._request(
            "DELETE",
            f"/v1/shipments/{quote(str(shipment_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    async def create(self, body: models.CreateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str) -> models.Shipment:
        """Create a shipment

        `POST /v1/shipments` (`createShipment`)
        """
        response = await self._request(
            "POST",
            "/v1/shipments",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data)

    async def list(self, *, cursor: str | None = None, limit: int | None = None, status: models.ShipmentStatus | None = None, extra_headers: Mapping[str, str] | None = None) -> AsyncPage[models.Shipment]:
        """List shipments

        `GET /v1/shipments` (`listShipments`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        if status is not None:
            query["status"] = cast(PageQueryValue, status)
        request = PageRequest(
            method="GET",
            url="/v1/shipments",
            query=query,
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return AsyncPage(self, request, first, scheme, cast_item=adapter.validate_python)

    async def retrieve(self, shipment_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Retrieve a shipment

        `GET /v1/shipments/{shipment_id}` (`retrieveShipment`)
        """
        response = await self._request(
            "GET",
            f"/v1/shipments/{quote(str(shipment_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data)

    async def update(self, shipment_id: str, body: models.UpdateShipmentRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.Shipment:
        """Update delivery instructions

        `PATCH /v1/shipments/{shipment_id}` (`updateShipment`)
        """
        response = await self._request(
            "PATCH",
            f"/v1/shipments/{quote(str(shipment_id), safe='')}",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.Shipment] = TypeAdapter(models.Shipment)
        return adapter.validate_python(response.data)
