# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Mapping

from pydantic import BeforeValidator, TypeAdapter

from .._kernel._constraints import constraint_validator
from .._kernel._serialization import encode_path_parameter
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class Tracking(SyncAPIResource):
    """The sync `tracking` resource."""

    def retrieve(self, tracking_number: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^PE-[A-Z0-9]{12}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.TrackingTimeline:
        """Retrieve a public tracking timeline

        `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^PE-[A-Z0-9]{12}$"}))]).validate_python(tracking_number, strict=True)
        response = self._request(
            "GET",
            "/v1/tracking/{tracking_number}".replace("{tracking_number}", encode_path_parameter("tracking_number", to_jsonable(tracking_number), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.TrackingTimeline] = TypeAdapter(models.TrackingTimeline)
        return adapter.validate_python(response.data, strict=True)


class AsyncTracking(AsyncAPIResource):
    """The async `tracking` resource."""

    async def retrieve(self, tracking_number: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^PE-[A-Z0-9]{12}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.TrackingTimeline:
        """Retrieve a public tracking timeline

        `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^PE-[A-Z0-9]{12}$"}))]).validate_python(tracking_number, strict=True)
        response = await self._request(
            "GET",
            "/v1/tracking/{tracking_number}".replace("{tracking_number}", encode_path_parameter("tracking_number", to_jsonable(tracking_number), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.TrackingTimeline] = TypeAdapter(models.TrackingTimeline)
        return adapter.validate_python(response.data, strict=True)
