# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from urllib.parse import quote

from typing import Mapping

from pydantic import TypeAdapter

from .._resource import AsyncAPIResource, SyncAPIResource
from .. import models


class Tracking(SyncAPIResource):
    """The sync `tracking` resource."""

    def retrieve(self, tracking_number: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.TrackingTimeline:
        """Retrieve a public tracking timeline

        `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
        """
        response = self._request(
            "GET",
            f"/v1/tracking/{quote(str(tracking_number), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.TrackingTimeline] = TypeAdapter(models.TrackingTimeline)
        return adapter.validate_python(response.data)


class AsyncTracking(AsyncAPIResource):
    """The async `tracking` resource."""

    async def retrieve(self, tracking_number: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.TrackingTimeline:
        """Retrieve a public tracking timeline

        `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
        """
        response = await self._request(
            "GET",
            f"/v1/tracking/{quote(str(tracking_number), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.TrackingTimeline] = TypeAdapter(models.TrackingTimeline)
        return adapter.validate_python(response.data)
