# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from urllib.parse import quote

from typing import Any, Mapping

from pydantic import TypeAdapter

from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class WebhookEndpoints(SyncAPIResource):
    """The sync `webhook_endpoints` resource."""

    def create(self, body: models.CreateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Register a webhook endpoint

        `POST /v1/webhook-endpoints` (`createWebhookEndpoint`)
        """
        response = self._request(
            "POST",
            "/v1/webhook-endpoints",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data)

    def list(self, *, cursor: str | None = None, limit: int | None = None, extra_headers: Mapping[str, str] | None = None) -> SyncPage[models.WebhookEndpoint]:
        """List webhook endpoints

        `GET /v1/webhook-endpoints` (`listWebhookEndpoints`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        request = PageRequest(
            method="GET",
            url="/v1/webhook-endpoints",
            query=query,
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return SyncPage(self, request, first, scheme, cast_item=adapter.validate_python)

    def remove(self, endpoint_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Delete a webhook endpoint

        `DELETE /v1/webhook-endpoints/{endpoint_id}` (`deleteWebhookEndpoint`)
        """
        self._request(
            "DELETE",
            f"/v1/webhook-endpoints/{quote(str(endpoint_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    def update(self, endpoint_id: str, body: models.UpdateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Update a webhook endpoint

        `PATCH /v1/webhook-endpoints/{endpoint_id}` (`updateWebhookEndpoint`)
        """
        response = self._request(
            "PATCH",
            f"/v1/webhook-endpoints/{quote(str(endpoint_id), safe='')}",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data)


class AsyncWebhookEndpoints(AsyncAPIResource):
    """The async `webhook_endpoints` resource."""

    async def create(self, body: models.CreateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Register a webhook endpoint

        `POST /v1/webhook-endpoints` (`createWebhookEndpoint`)
        """
        response = await self._request(
            "POST",
            "/v1/webhook-endpoints",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data)

    async def list(self, *, cursor: str | None = None, limit: int | None = None, extra_headers: Mapping[str, str] | None = None) -> AsyncPage[models.WebhookEndpoint]:
        """List webhook endpoints

        `GET /v1/webhook-endpoints` (`listWebhookEndpoints`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = cursor
        if limit is not None:
            query["limit"] = limit
        request = PageRequest(
            method="GET",
            url="/v1/webhook-endpoints",
            query=query,
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return AsyncPage(self, request, first, scheme, cast_item=adapter.validate_python)

    async def remove(self, endpoint_id: str, *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Delete a webhook endpoint

        `DELETE /v1/webhook-endpoints/{endpoint_id}` (`deleteWebhookEndpoint`)
        """
        await self._request(
            "DELETE",
            f"/v1/webhook-endpoints/{quote(str(endpoint_id), safe='')}",
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    async def update(self, endpoint_id: str, body: models.UpdateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Update a webhook endpoint

        `PATCH /v1/webhook-endpoints/{endpoint_id}` (`updateWebhookEndpoint`)
        """
        response = await self._request(
            "PATCH",
            f"/v1/webhook-endpoints/{quote(str(endpoint_id), safe='')}",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data)
