# Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Any, Mapping

from pydantic import BeforeValidator, TypeAdapter

from .._kernel._constraints import constraint_validator
from .._kernel._pagination import AsyncPage, CursorScheme, SyncPage
from .._kernel._pagination_locators import PageQueryValue, PageRequest
from .._kernel._serialization import encode_path_parameter
from .._resource import AsyncAPIResource, SyncAPIResource, to_jsonable
from .. import models


class WebhookEndpoints(SyncAPIResource):
    """The sync `webhook_endpoints` resource."""

    def create(self, body: models.CreateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Register a webhook endpoint

        `POST /v1/webhook-endpoints` (`createWebhookEndpoint`)
        """
        TypeAdapter(models.CreateWebhookEndpointRequest).validate_python(body, strict=True)
        response = self._request(
            "POST",
            "/v1/webhook-endpoints",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data, strict=True)

    def get(self, endpoint_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Retrieve a webhook endpoint

        `GET /v1/webhook-endpoints/{endpoint_id}` (`retrieveWebhookEndpoint`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))]).validate_python(endpoint_id, strict=True)
        response = self._request(
            "GET",
            "/v1/webhook-endpoints/{endpoint_id}".replace("{endpoint_id}", encode_path_parameter("endpoint_id", to_jsonable(endpoint_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data, strict=True)

    def list(self, *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> SyncPage[models.WebhookEndpoint]:
        """List webhook endpoints

        `GET /v1/webhook-endpoints` (`listWebhookEndpoints`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/webhook-endpoints",
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return SyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.WebhookEndpointPage).validate_python(envelope, strict=True))

    def remove(self, endpoint_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Delete a webhook endpoint

        `DELETE /v1/webhook-endpoints/{endpoint_id}` (`deleteWebhookEndpoint`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))]).validate_python(endpoint_id, strict=True)
        self._request(
            "DELETE",
            "/v1/webhook-endpoints/{endpoint_id}".replace("{endpoint_id}", encode_path_parameter("endpoint_id", to_jsonable(endpoint_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    def update(self, endpoint_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))], body: models.UpdateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Update a webhook endpoint

        `PATCH /v1/webhook-endpoints/{endpoint_id}` (`updateWebhookEndpoint`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))]).validate_python(endpoint_id, strict=True)
        TypeAdapter(models.UpdateWebhookEndpointRequest).validate_python(body, strict=True)
        response = self._request(
            "PATCH",
            "/v1/webhook-endpoints/{endpoint_id}".replace("{endpoint_id}", encode_path_parameter("endpoint_id", to_jsonable(endpoint_id), {"style": "simple", "explode": False, "allowReserved": False})),
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data, strict=True)


class AsyncWebhookEndpoints(AsyncAPIResource):
    """The async `webhook_endpoints` resource."""

    async def create(self, body: models.CreateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Register a webhook endpoint

        `POST /v1/webhook-endpoints` (`createWebhookEndpoint`)
        """
        TypeAdapter(models.CreateWebhookEndpointRequest).validate_python(body, strict=True)
        response = await self._request(
            "POST",
            "/v1/webhook-endpoints",
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data, strict=True)

    async def get(self, endpoint_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Retrieve a webhook endpoint

        `GET /v1/webhook-endpoints/{endpoint_id}` (`retrieveWebhookEndpoint`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))]).validate_python(endpoint_id, strict=True)
        response = await self._request(
            "GET",
            "/v1/webhook-endpoints/{endpoint_id}".replace("{endpoint_id}", encode_path_parameter("endpoint_id", to_jsonable(endpoint_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data, strict=True)

    async def list(self, *, cursor: Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))] | None = None, limit: Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))] | None = None, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> AsyncPage[models.WebhookEndpoint]:
        """List webhook endpoints

        `GET /v1/webhook-endpoints` (`listWebhookEndpoints`)

        Paginated (`cursor_page`): iterate the returned page to walk every item.
        """
        if cursor is not None:
            TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"minLength": 1}))]).validate_python(cursor, strict=True)
        if limit is not None:
            TypeAdapter(Annotated[int, BeforeValidator(constraint_validator({"minimum": 1, "maximum": 100}))]).validate_python(limit, strict=True)
        query: dict[str, PageQueryValue] = {}
        if cursor is not None:
            query["cursor"] = to_jsonable(cursor)
        if limit is not None:
            query["limit"] = to_jsonable(limit)
        request = PageRequest(
            method="GET",
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
            url="/v1/webhook-endpoints",
            query=query,
            query_styles={"cursor": {"style": "form", "explode": True, "allowReserved": False}, "limit": {"style": "form", "explode": True, "allowReserved": False}},
            headers=extra_headers,
        )
        first = await self.request_page(request)
        scheme = CursorScheme(
            request_cursor="query.cursor",
            response_items="$.data",
            response_next_cursor="$.next_cursor",
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return AsyncPage(self, request, first, scheme, cast_item=lambda item: adapter.validate_python(item, strict=True), validate_body=lambda envelope: TypeAdapter(models.WebhookEndpointPage).validate_python(envelope, strict=True))

    async def remove(self, endpoint_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> None:
        """Delete a webhook endpoint

        `DELETE /v1/webhook-endpoints/{endpoint_id}` (`deleteWebhookEndpoint`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))]).validate_python(endpoint_id, strict=True)
        await self._request(
            "DELETE",
            "/v1/webhook-endpoints/{endpoint_id}".replace("{endpoint_id}", encode_path_parameter("endpoint_id", to_jsonable(endpoint_id), {"style": "simple", "explode": False, "allowReserved": False})),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        return None

    async def update(self, endpoint_id: Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))], body: models.UpdateWebhookEndpointRequest | Mapping[str, Any], *, timeout_ms: float | None = None, extra_headers: Mapping[str, str] | None = None, idempotency_key: str | None = None) -> models.WebhookEndpoint:
        """Update a webhook endpoint

        `PATCH /v1/webhook-endpoints/{endpoint_id}` (`updateWebhookEndpoint`)
        """
        TypeAdapter(Annotated[str, BeforeValidator(constraint_validator({"pattern": "^whe_[a-z0-9]{20}$"}))]).validate_python(endpoint_id, strict=True)
        TypeAdapter(models.UpdateWebhookEndpointRequest).validate_python(body, strict=True)
        response = await self._request(
            "PATCH",
            "/v1/webhook-endpoints/{endpoint_id}".replace("{endpoint_id}", encode_path_parameter("endpoint_id", to_jsonable(endpoint_id), {"style": "simple", "explode": False, "allowReserved": False})),
            body=to_jsonable(body),
            headers=extra_headers,
            timeout_ms=timeout_ms,
            idempotency_key=idempotency_key,
        )
        adapter: TypeAdapter[models.WebhookEndpoint] = TypeAdapter(models.WebhookEndpoint)
        return adapter.validate_python(response.data, strict=True)
